#!/usr/bin/env python3
# -*- coding: utf-8 -*-
'''
    Constants
'''

# Limit on number values for RGB, etc.
NUM_MIN = 0
NUM_MAX = 255

# Limit on Degrees as used for Hue and Bearing
DEG_MIN = 0
DEG_MAX = 360

# Limit in level, etc. used for Brightness, percentage, etc.
LEVEL_MIN = 0
LEVEL_MAX = 100

OFF = 0
ON = 1
ONOFF = [
    OFF,
    ON,
]

################################################################################
# Hardware types
################################################################################
HTYPE_RFXTRX315 = 0
HTYPE_RFXTRX433 = 1
HTYPE_RFXLAN = 2
HTYPE_DOMOTICZ = 3
HTYPE_P1SMARTMETER = 4
HTYPE_P1SMARTMETERLAN = 5
HTYPE_YOULESS = 6
HTYPE_TE923 = 7
HTYPE_REGO6XX = 8
HTYPE_TTN_MQTT = 9
HTYPE_DAVISVANTAGE = 10
HTYPE_VOLCRAFTCO20 = 11
HTYPE_1WIRE = 12
HTYPE_RASPBERRYBMP085 = 13
HTYPE_WUNDERGROUND = 14
HTYPE_DUMMY = 15
HTYPE_PIFACE = 16
HTYPE_S0SMARTMETERUSB = 17
HTYPE_OPENTHERMGATEWAY = 18
HTYPE_TELEINFOMETER = 19
HTYPE_OPENTHERMGATEWAYTCP = 20
HTYPE_OPENZWAVE = 21
HTYPE_LIMITLESSLIGHTS = 22
HTYPE_SYSTEM = 23
HTYPE_ENOCEANESP2 = 24
HTYPE_DARKSKY = 25
HTYPE_SOLAREDGETCP = 26
HTYPE_SBFSPOT = 27
HTYPE_ICYTHERMOSTAT = 28
HTYPE_WOL = 29
HTYPE_PVOUTPUT_INPUT = 30
HTYPE_ENOCEANESP3 = 31
HTYPE_RASPBERRYGPIO = 32
HTYPE_METEOSTICK = 33
HTYPE_TOONTHERMOSTAT = 34
HTYPE_ECODEVICES = 35
HTYPE_HARMONY_HUB = 36
HTYPE_MOCHAD = 37
HTYPE_PHILIPS_HUE = 38
HTYPE_EVOHOME_SERIAL = 39
HTYPE_EVOHOME_SCRIPT = 40
HTYPE_MYSENSORSUSB = 41
HTYPE_MYSENSORSTCP = 42
HTYPE_MQTT = 43
HTYPE_FRITZBOX = 44
HTYPE_ETH8020 = 45
HTYPE_RFLINKUSB = 46
HTYPE_KMTRONICUSB = 47
HTYPE_KMTRONICTCP = 48
HTYPE_SOLARMAXTCP = 49
HTYPE_KMTRONIC433 = 50
HTYPE_PINGER = 51
HTYPE_NEST = 52
HTYPE_THERMOSMART = 53
HTYPE_NETATMO = 54
HTYPE_KODI = 55
HTYPE_ANNATHERMOSTAT = 56
HTYPE_WINDDELEN = 57
HTYPE_SATELINTEGRA = 58
HTYPE_TELLSTICK = 59
HTYPE_LOGITECHMEDIASERVER = 60
HTYPE_RFXTRX868 = 61
HTYPE_RFLINKTCP = 62
HTYPE_COMM5TCP = 63
HTYPE_SOLAREDGEAPI = 64
HTYPE_CURRENTCOSTMETER = 65
HTYPE_CURRENTCOSTMETERLAN = 66
HTYPE_DOMOTICZINTERNAL = 67
HTYPE_NEFITEASTLAN = 68
HTYPE_PANASONICTV = 69
HTYPE_OPENWEBNETTCP = 70
HTYPE_RASPBERRYHTU21D = 71
HTYPE_ATAGONE = 72
HTYPE_STERBOX = 73
HTYPE_HTTPPOLLER = 74
HTYPE_EVOHOME_WEB = 75
HTYPE_RAVEN = 76
HTYPE_S0SMARTMETERTCP = 77
HTYPE_RESERVED_FOR_YOU_1 = 78
HTYPE_ACCUWEATHER = 79
HTYPE_COMM5SERIAL = 80
HTYPE_EC3KMETERTCP = 81
HTYPE_BLEBOX = 82
HTYPE_OPENWEATHERMAP = 83
HTYPE_GOODWEAPI = 84
HTYPE_RASPBERRYTSL2561 = 85
HTYPE_DAIKIN = 86
HTYPE_HEOS = 87
HTYPE_MULTIFUN = 88
HTYPE_ZIBLUEUSB = 89
HTYPE_ZIBLUETCP = 90
HTYPE_YEELIGHT = 91
HTYPE_MYSENSORSMQTT = 92
HTYPE_RASPBERRYPCF8574 = 93
HTYPE_PYTHONPLUGIN = 94
HTYPE_XIAOMIGATEWAY = 95
HTYPE_RASPBERRYBME280 = 96
HTYPE_ARILUX = 97
HTYPE_OPENWEBNETUSB = 98
HTYPE_INTERGASINCOMFORTLAN2RF = 99
HTYPE_RELAYNET = 100
HTYPE_KMTRONICUDP = 101
HTYPE_SYSFSGPIO = 102
HTYPE_RTL433 = 103
HTYPE_ONKYOAVTCP = 104
HTYPE_RESERVED_FOR_YOU_2 = 105
HTYPE_EVOHOME_TCP = 106
HTYPE_USBTINGATEWAY = 107
HTYPE_ENPHASEAPI = 108
HTYPE_RASPBERRYMCP23017 = 109
HTYPE_EHOUSETCP = 110
HTYPE_COMM5SMTCP = 111
HTYPE_NEST_OAUTHAPI = 112
HTYPE_ECOCOMPTEUR = 113
HTYPE_HONEYWELL = 114
HTYPE_TADO = 115
HTYPE_DENKOVIHTTPDEVICES = 116
HTYPE_DENKOVIUSBDEVICES = 117
HTYPE_DENKOVITCPDEVICES = 118
