#!/usr/bin/env python3
# -*- coding: utf-8 -*-


class Settings:

    KEY_ACCEPTNEWHARDWARE = "AcceptNewHardware"
    KEY_ACTIVETIMERPLAN = "ActiveTimerPlan"
    KEY_ALLOWWIDGETORDERING = "AllowWidgetOrdering"
    KEY_AUTHENTICATIONMETHOD = "AuthenticationMethod"
    KEY_BATTERLOWLEVEL = "BatterLowLevel"
    KEY_CHECKFORUPDATES = "UseAutoUpdate"
    KEY_CLICKATELLAPI = "ClickatellAPI"
    KEY_CLICKATELLENABLED = "ClickatellEnabled"
    KEY_CLICKATELLFROM = "ClickatellFrom"
    KEY_CLICKATELLPASSWORD = "ClickatellPassword"
    KEY_CLICKATELLTO = "ClickatellTo"
    KEY_CLICKATELLUSER = "ClickatellUser"
    KEY_CM113DISPLAYTYPE = "CM113DisplayType"
    KEY_COSTENERGY = "CostEnergy"
    KEY_COSTENERGYR1 = "CostEnergyR1"
    KEY_COSTENERGYR2 = "CostEnergyR2"
    KEY_COSTENERGYT2 = "CostEnergyT2"
    KEY_COSTGAS = "CostGas"
    KEY_COSTWATER = "CostWater"
    KEY_DASHBOARDTYPE = "DashboardType"
    KEY_DB_VERSION = "DB_Version"
    KEY_DEGREEDAYSBASETEMPERATURE = "DegreeDaysBaseTemperature"
    KEY_DISABLEDZVENTSSYSTEM = "DisableDzVentsSystem"
    KEY_DOORBELLCOMMAND = "DoorbellCommand"
    KEY_DZVENTSLOGLEVEL = "DzVentsLogLevel"
    KEY_ELECTRICVOLTAGE = "ElectricVoltage"
    KEY_EMAILASATTACHMENT = "EmailAsAttachment"
    KEY_EMAILENABLED = "EmailEnabled"
    KEY_EMAILFROM = "EmailFrom"
    KEY_EMAILPASSWORD = "EmailPassword"
    KEY_EMAILPORT = "EmailPort"
    KEY_EMAILSERVER = "EmailServer"
    KEY_EMAILTO = "EmailTo"
    KEY_EMAILUSERNAME = "EmailUsername"
    KEY_ENABLEAUTOBACKUP = "UseAutoBackup"
    KEY_ENABLEEVENTSCRIPTSYSTEM = "EnableEventScriptSystem"
    KEY_ENABLETABCUSTOM = "EnableTabCustom"
    KEY_ENABLETABFLOORPLANS = "EnableTabFloorplans"
    KEY_ENABLETABLIGHTS = "EnableTabLights"
    KEY_ENABLETABSCENES = "EnableTabScenes"
    KEY_ENABLETABTEMP = "EnableTabTemp"
    KEY_ENABLETABUTILITY = "EnableTabUtility"
    KEY_ENABLETABWEATHER = "EnableTabWeather"
    KEY_ENERGYDIVIDER = "EnergyDivider"
    KEY_FLOORPLANACTIVEOPACITY = "FloorplanActiveOpacity"
    KEY_FLOORPLANANIMATEZOOM = "FloorplanAnimateZoom"
    KEY_FLOORPLANFULLSCREENMODE = "FloorplanFullscreenMode"
    KEY_FLOORPLANINACTIVEOPACITY = "FloorplanInactiveOpacity"
    KEY_FLOORPLANPOPUPDELAY = "FloorplanPopupDelay"
    KEY_FLOORPLANROOMCOLOUR = "FloorplanRoomColour"
    KEY_FLOORPLANSHOWSCENENAMES = "FloorplanShowSceneNames"
    KEY_FLOORPLANSHOWSENSORVALUES = "FloorplanShowSensorValues"
    KEY_FLOORPLANSHOWSWITCHVALUES = "FloorplanShowSwitchValues"
    KEY_GASDIVIDER = "GasDivider"
    KEY_GCMENABLED = "GCMEnabled"
    KEY_HIDEDISABLEDHARDWARESENSORS = "HideDisabledHardwareSensors"
    KEY_HTTPENABLED = "HTTPEnabled"
    KEY_HTTPFIELD1 = "HTTPField1"
    KEY_HTTPFIELD2 = "HTTPField2"
    KEY_HTTPFIELD3 = "HTTPField3"
    KEY_HTTPFIELD4 = "HTTPField4"
    KEY_HTTPPOSTCONTENTTYPE = "HTTPPostContentType"
    KEY_HTTPPOSTDATA = "HTTPPostData"
    KEY_HTTPPOSTHEADERS = "HTTPPostHeaders"
    KEY_HTTPTO = "HTTPTo"
    KEY_HTTPURL = "HTTPURL"
    KEY_IFTTTAPI = "IFTTTAPI"
    KEY_IFTTTENABLED = "IFTTTEnabled"
    KEY_KODIENABLED = "KodiEnabled"
    KEY_KODIIPADDRESS = "KodiIPAddress"
    KEY_KODIPORT = "KodiPort"
    KEY_KODITIMETOLIVE = "KodiTimeToLive"
    KEY_LANGUAGE = "Language"
    KEY_LIGHTHISTORYDAYS = "LightHistoryDays"
    KEY_LMSDURATION = "LmsDuration"
    KEY_LMSENABLED = "LmsEnabled"
    KEY_LMSPLAYERMAC = "LmsPlayerMac"
    KEY_LOCATION = "Location"
    KEY_LOGEVENTSCRIPTTRIGGER = "LogEventScriptTrigger"
    KEY_MOBILETYPE = "MobileType"
    KEY_MYDOMOTICZSUBSYSTEMS = "MyDomoticzSubsystems"
    KEY_MYDOMOTICZUSERID = "MyDomoticzUserId"
    KEY_NMAAPI = "NMAAPI"
    KEY_NMAENABLED = "NMAEnabled"
    KEY_NOTIFICATIONSENSORINTERVAL = "NotificationSensorInterval"
    KEY_NOTIFICATIONSWITCHINTERVAL = "NotificationSwitchInterval"
    KEY_ONEWIRESENSORPOLLPERIOD = "OneWireSensorPollPeriod"
    KEY_ONEWIRESWITCHPOLLPERIOD = "OneWireSwitchPollPeriod"
    KEY_PROTECTIONPASSWORD = "ProtectionPassword"
    KEY_PROWLAPI = "ProwlAPI"
    KEY_PROWLENABLED = "ProwlEnabled"
    KEY_PUSHALOTAPI = "PushALotAPI"
    KEY_PUSHALOTENABLED = "PushALotEnabled"
    KEY_PUSHBULLETAPI = "PushbulletAPI"
    KEY_PUSHBULLETENABLED = "PushbulletEnabled"
    KEY_PUSHOVERAPI = "PushoverAPI"
    KEY_PUSHOVERENABLED = "PushoverEnabled"
    KEY_PUSHOVERUSER = "PushoverUser"
    KEY_PUSHSAFERAPI = "PushsaferAPI"
    KEY_PUSHSAFERENABLED = "PushsaferEnabled"
    KEY_PUSHSAFERIMAGE = "PushsaferImage"
    KEY_RANDOMTIMERFRAME = "RandomTimerFrame"
    KEY_RASPCAMPARAMS = "RaspCamParams"
    KEY_RELEASECHANNEL = "ReleaseChannel"
    KEY_REMOTESHAREDPORT = "RemoteSharedPort"
    KEY_SECONDELAY = "SecOnDelay"
    KEY_SECPASSWORD = "SecPassword"
    KEY_SECSTATUS = "SecStatus"
    KEY_SENDERRORNOTIFICATIONS = "SendErrorNotifications"
    KEY_SENDERRORSASNOTIFICATION = "SendErrorsAsNotification"
    KEY_SENSORTIMEOUT = "SensorTimeout"
    KEY_SENSORTIMEOUTNOTIFICATION = "SensorTimeoutNotification"
    KEY_SHORTLOGDAYS = "ShortLogDays"
    KEY_SHORTLOGINTERVAL = "ShortLogInterval"
    KEY_SHOWUPDATEEFFECT = "ShowUpdateEffect"
    KEY_SMARTMETERTYPE = "SmartMeterType"
    KEY_SUBSYSTEMAPPS = "SubsystemApps"
    KEY_SUBSYSTEMHTTP = "SubsystemHttp"
    KEY_SUBSYSTEMSHARED = "SubsystemShared"
    KEY_TELEGRAMAPI = "TelegramAPI"
    KEY_TELEGRAMCHAT = "TelegramChat"
    KEY_TELEGRAMENABLED = "TelegramEnabled"
    KEY_TEMPAWAY = "TempAway"
    KEY_TEMPCOMFORT = "TempComfort"
    KEY_TEMPHOME = "TempHome"
    KEY_TEMPUNIT = "TempUnit"
    KEY_THEMES = "Themes"
    KEY_TITLE = "Title"
    KEY_USEEMAILINNOTIFICATIONS = "UseEmailInNotifications"
    KEY_UVCPARAMS = "UVCParams"
    KEY_WATERDIVIDER = "WaterDivider"
    KEY_WEBLOCALNETWORKS = "WebLocalNetworks"
    KEY_WEBPASSWORD = "WebPassword"
    KEY_WEBREMOTEPROXYIPS = "WebRemoteProxyIPs"
    KEY_WEBUSERNAME = "WebUserName"
    KEY_WEIGHTUNIT = "WeightUnit"
    KEY_WINDUNIT = "WindUnit"
    # KEY_ZWAVEAEOTECBLINKENABLED = "ZWaveAeotecBlinkEnabled"
    # KEY_ZWAVEENABLEDEBUG = "ZWaveEnableDebug"
    # KEY_ZWAVEENABLENIGHTLYNETWORKHEAL = "ZWaveEnableNightlyNetworkHeal"
    # KEY_ZWAVENETWORKKEY = "ZWaveNetworkKey"
    # KEY_ZWAVEPOLLINTERVAL = "ZWavePollInterval"

    KEYS = [
        KEY_ACCEPTNEWHARDWARE,
        KEY_ACTIVETIMERPLAN,
        KEY_ALLOWWIDGETORDERING,
        KEY_AUTHENTICATIONMETHOD,
        KEY_BATTERLOWLEVEL,
        KEY_CHECKFORUPDATES,
        KEY_CLICKATELLAPI,
        KEY_CLICKATELLENABLED,
        KEY_CLICKATELLFROM,
        KEY_CLICKATELLPASSWORD,
        KEY_CLICKATELLTO,
        KEY_CLICKATELLUSER,
        KEY_CM113DISPLAYTYPE,
        KEY_COSTENERGY,
        KEY_COSTENERGYR1,
        KEY_COSTENERGYR2,
        KEY_COSTENERGYT2,
        KEY_COSTGAS,
        KEY_COSTWATER,
        KEY_DASHBOARDTYPE,
        # KEY_DB_VERSION,
        KEY_DEGREEDAYSBASETEMPERATURE,
        KEY_DISABLEDZVENTSSYSTEM,
        KEY_DOORBELLCOMMAND,
        KEY_DZVENTSLOGLEVEL,
        KEY_ELECTRICVOLTAGE,
        KEY_EMAILASATTACHMENT,
        KEY_EMAILENABLED,
        KEY_EMAILFROM,
        KEY_EMAILPASSWORD,
        KEY_EMAILPORT,
        KEY_EMAILSERVER,
        KEY_EMAILTO,
        KEY_EMAILUSERNAME,
        KEY_ENABLEAUTOBACKUP,
        KEY_ENABLEEVENTSCRIPTSYSTEM,
        KEY_ENABLETABCUSTOM,
        KEY_ENABLETABFLOORPLANS,
        KEY_ENABLETABLIGHTS,
        KEY_ENABLETABSCENES,
        KEY_ENABLETABTEMP,
        KEY_ENABLETABUTILITY,
        KEY_ENABLETABWEATHER,
        KEY_ENERGYDIVIDER,
        KEY_FLOORPLANACTIVEOPACITY,
        KEY_FLOORPLANANIMATEZOOM,
        KEY_FLOORPLANFULLSCREENMODE,
        KEY_FLOORPLANINACTIVEOPACITY,
        KEY_FLOORPLANPOPUPDELAY,
        KEY_FLOORPLANROOMCOLOUR,
        KEY_FLOORPLANSHOWSCENENAMES,
        KEY_FLOORPLANSHOWSENSORVALUES,
        KEY_FLOORPLANSHOWSWITCHVALUES,
        KEY_GASDIVIDER,
        KEY_GCMENABLED,
        KEY_HIDEDISABLEDHARDWARESENSORS,
        KEY_HTTPENABLED,
        KEY_HTTPFIELD1,
        KEY_HTTPFIELD2,
        KEY_HTTPFIELD3,
        KEY_HTTPFIELD4,
        KEY_HTTPPOSTCONTENTTYPE,
        KEY_HTTPPOSTDATA,
        KEY_HTTPPOSTHEADERS,
        KEY_HTTPTO,
        KEY_HTTPURL,
        KEY_IFTTTAPI,
        KEY_IFTTTENABLED,
        KEY_KODIENABLED,
        KEY_KODIIPADDRESS,
        KEY_KODIPORT,
        KEY_KODITIMETOLIVE,
        KEY_LANGUAGE,
        KEY_LIGHTHISTORYDAYS,
        KEY_LMSDURATION,
        KEY_LMSENABLED,
        KEY_LMSPLAYERMAC,
        KEY_LOCATION,
        KEY_LOGEVENTSCRIPTTRIGGER,
        KEY_MOBILETYPE,
        KEY_MYDOMOTICZSUBSYSTEMS,
        KEY_MYDOMOTICZUSERID,
        KEY_NMAAPI,
        KEY_NMAENABLED,
        KEY_NOTIFICATIONSENSORINTERVAL,
        KEY_NOTIFICATIONSWITCHINTERVAL,
        KEY_ONEWIRESENSORPOLLPERIOD,
        KEY_ONEWIRESWITCHPOLLPERIOD,
        KEY_PROTECTIONPASSWORD,
        KEY_PROWLAPI,
        KEY_PROWLENABLED,
        KEY_PUSHALOTAPI,
        KEY_PUSHALOTENABLED,
        KEY_PUSHBULLETAPI,
        KEY_PUSHBULLETENABLED,
        KEY_PUSHOVERAPI,
        KEY_PUSHOVERENABLED,
        KEY_PUSHOVERUSER,
        KEY_PUSHSAFERAPI,
        KEY_PUSHSAFERENABLED,
        KEY_PUSHSAFERIMAGE,
        KEY_RANDOMTIMERFRAME,
        KEY_RASPCAMPARAMS,
        KEY_RELEASECHANNEL,
        KEY_REMOTESHAREDPORT,
        KEY_SECONDELAY,
        KEY_SECPASSWORD,
        KEY_SECSTATUS,
        KEY_SENDERRORNOTIFICATIONS,
        KEY_SENDERRORSASNOTIFICATION,
        KEY_SENSORTIMEOUT,
        KEY_SENSORTIMEOUTNOTIFICATION,
        KEY_SHORTLOGDAYS,
        KEY_SHORTLOGINTERVAL,
        KEY_SHOWUPDATEEFFECT,
        KEY_SMARTMETERTYPE,
        KEY_SUBSYSTEMAPPS,
        KEY_SUBSYSTEMHTTP,
        KEY_SUBSYSTEMSHARED,
        KEY_TELEGRAMAPI,
        KEY_TELEGRAMCHAT,
        KEY_TELEGRAMENABLED,
        KEY_TEMPAWAY,
        KEY_TEMPCOMFORT,
        KEY_TEMPHOME,
        KEY_TEMPUNIT,
        KEY_THEMES,
        KEY_TITLE,
        KEY_USEEMAILINNOTIFICATIONS,
        KEY_UVCPARAMS,
        KEY_WATERDIVIDER,
        KEY_WEBLOCALNETWORKS,
        KEY_WEBPASSWORD,
        KEY_WEBREMOTEPROXYIPS,
        KEY_WEBUSERNAME,
        KEY_WEIGHTUNIT,
        KEY_WINDUNIT,
        # KEY_ZWAVEAEOTECBLINKENABLED,
        # KEY_ZWAVEENABLEDEBUG,
        # KEY_ZWAVEENABLENIGHTLYNETWORKHEAL,
        # KEY_ZWAVENETWORKKEY,
        # KEY_ZWAVEPOLLINTERVAL,
    ]

    KEY_SWITCHES = [
        # System
        KEY_ACCEPTNEWHARDWARE,
        KEY_ALLOWWIDGETORDERING,
        KEY_CHECKFORUPDATES,
        KEY_ENABLEAUTOBACKUP,
        KEY_HIDEDISABLEDHARDWARESENSORS,
        KEY_SHOWUPDATEEFFECT,
        KEY_SUBSYSTEMAPPS,
        KEY_SUBSYSTEMHTTP,
        KEY_SUBSYSTEMSHARED,
        KEY_ENABLETABCUSTOM,
        KEY_ENABLETABFLOORPLANS,
        KEY_ENABLETABLIGHTS,
        KEY_ENABLETABSCENES,
        KEY_ENABLETABTEMP,
        KEY_ENABLETABUTILITY,
        KEY_ENABLETABWEATHER,
        # Log History
        # Notifications
        KEY_CLICKATELLENABLED,
        KEY_PROWLENABLED,
        KEY_PUSHBULLETENABLED,
        KEY_PUSHSAFERENABLED,
        KEY_PUSHOVERENABLED,
        KEY_PUSHALOTENABLED,
        KEY_HTTPENABLED,
        KEY_IFTTTENABLED,
        KEY_KODIENABLED,
        KEY_LMSENABLED,
        KEY_GCMENABLED,
        KEY_TELEGRAMENABLED,
        # Email setup
        KEY_EMAILASATTACHMENT,
        KEY_EMAILENABLED,
        KEY_SENDERRORSASNOTIFICATION,
        KEY_USEEMAILINNOTIFICATIONS,
        # Meter/Counters
        # Floorplan
        KEY_FLOORPLANFULLSCREENMODE,
        KEY_FLOORPLANANIMATEZOOM,
        KEY_FLOORPLANSHOWSENSORVALUES,
        KEY_FLOORPLANSHOWSCENENAMES,
        KEY_FLOORPLANSHOWSWITCHVALUES,
        # Other
        KEY_ENABLEEVENTSCRIPTSYSTEM,
        KEY_LOGEVENTSCRIPTTRIGGER,
        KEY_DISABLEDZVENTSSYSTEM,
    ]

    AUTHENTICATION_METHOD_LOGIN_PAGE = 0
    AUTHENTICATION_METHOD_BASIC_AUTH = 1
    AUTHENTICATION_METHODS = [
        AUTHENTICATION_METHOD_LOGIN_PAGE,
        AUTHENTICATION_METHOD_BASIC_AUTH,
    ]

    SETTING_OFF = 0
    SETTING_ON = 1
    SETTING_VALUES = [
        SETTING_OFF,
        SETTING_ON,
    ]

    CM113_DISPLAY_TYPE_AMPERE = 0
    CM113_DISPLAY_TYPE_WATT = 1
    CM113_DISPLAY_TYPES = [
        CM113_DISPLAY_TYPE_AMPERE,
        CM113_DISPLAY_TYPE_WATT,
    ]

    DASHBOARD_TYPE_NORMAL = 0
    DASHBOARD_TYPE_COMPACT = 1
    DASHBOARD_TYPE_MOBILE = 2
    DASHBOARD_TYPE_FLOORPLAN = 3
    DASHBOARD_TYPES = [
        DASHBOARD_TYPE_NORMAL,
        DASHBOARD_TYPE_COMPACT,
        DASHBOARD_TYPE_MOBILE,
        DASHBOARD_TYPE_FLOORPLAN,
    ]

    MOBILE_TYPE_MOBILE = 0
    MOBILE_TYPE_DASHBOARD = 1
    MOBILE_TYPES = [
        MOBILE_TYPE_MOBILE,
        MOBILE_TYPE_DASHBOARD,
    ]

    SMARTMETER_TYPE_WITH_DECIMALS = 0
    SMARTMETER_TYPE_NO_DECIMALS = 1
    SMARTMETER_TYPES = [
        SMARTMETER_TYPE_WITH_DECIMALS,
        SMARTMETER_TYPE_NO_DECIMALS,
    ]

    TEMP_UNIT_CELSIUS = 0
    TEMP_UNIT_FAHRENHEIT = 1
    TEMP_UNITS = [
        TEMP_UNIT_CELSIUS,
        TEMP_UNIT_FAHRENHEIT,
    ]

    WEIGHT_UNIT_KILOGRAMS = 0
    WEIGHT_UNIT_POUNDS = 1
    WEIGHT_UNITS = [
        WEIGHT_UNIT_KILOGRAMS,
        WEIGHT_UNIT_POUNDS,
    ]

    WIND_UNIT_MS = 0
    WIND_UNIT_KMH = 1
    WIND_UNIT_MPH = 2
    WIND_UNIT_KNOTS = 3
    WIND_UNIT_BEAUFORT = 4
    WIND_UNITS = [
        WIND_UNIT_MS,
        WIND_UNIT_KMH,
        WIND_UNIT_MPH,
        WIND_UNIT_KNOTS,
        WIND_UNIT_BEAUFORT,
    ]
